### ISSUE TITLE
OccurrenceID URL contains extra parameter

### ISSUE THREAD

**Issue by rdmpage** [mvz-vertnet/mvz-herp#40]
All the occurrenceID fields are of the form http://arctos.database.museum/guid/MVZ:Herp:(id)?seid=(), where "?seid=1800680" looks like a session variable(?) Surely this parameter has no place in a persistent identifier? If the seid changes between exports, it is likely that aggregators such as GBIF will think that occurrenceID that different only in seid values will be distinct occurrences, leading to potential duplication.

**Comment by rdmpage** [comment]
I've just noticed the urn's for MVZ records are of the form urn:occurrence:Arctos:MVZ:Herp:(id):(seid) so maybe said is a version string? In any event, why not have the unversioned URL as the occurrenceID?

**Comment by tucotuco** [comment]
@rdmpage Thanks for the careful scrutiny and the comments.

The seid parameter at the end of the URL serving as the GUID in Arctos is neither a session variable, nor a version string. It is a specimen event id. The URLs given as occurrenceIDs identify an organisms participation in Event, which is valid concept for an occurrence. Arctos does indeed have organisms that participate in multiple occurrences (such as biopsies). You can see an example of this with http://www.gbif.org/occurrence/search?CATALOG_NUMBER=142856&DATASET_KEY=b15d4952-7d20-46f1-8a3e-556a512b04c5.

Investigating in preparation for a response, I found that the exports for the Arctos data are fine in IPT, which is why GBIF can show the multiple occurrences for an organism. However, the index id constructor for the VertNet portal uses the catalogNumber if it exists. This results in only one of the occurrences surviving. This issue has been logged for the indexer at https://github.com/VertNet/dwc-indexer/issues/40

Closing the issue here.
